#!/bin/sh

source ./deploy.conf

echo Creating pxeboot external bridge ...

docker network create \
        --internal \
        --attachable \
        --driver 'bridge' \
        --subnet '192.168.8.0/24' \
        --ip-range '192.168.8.0/28' \
        --opt 'com.docker.network.bridge.name=br-pxeboot' \
        pxeboot

echo 0 > /proc/sys/net/bridge/bridge-nf-call-iptables

echo Creating vxlan adapter ...
ip link add vx0 type vxlan id 100 remote $raapp_wg_tun_ip dstport 4789

brctl addif br-pxeboot vx0
ip link set vx0 up

echo Launching Docker compose cluster ...
docker-compose up

echo Removing pxeboot external bridge ...
docker network rm pxeboot

